### ISSUE TITLE
Response agent implementation problems/Tasks [local interface]

### ISSUE THREAD

**Issue by ranguy9304** [inquisitour/Knowledge-Based-Agent#17]
In agent.py file in local Interface the response is generated through an agent executor, this agent executor already has the tools for database retrieval and still the context in manually generated and passed on.

**TODO**:
- Remove manual context generation and let the tools execute as needed.
- EmbeddingRetriever Class is in agent.py file move it or create a new module for the same
- Some unidentified problem with EmbeddingRetriever fix that.
- Due to the continuous execution of streamlit many initializations functions are called repeatedly, create a terminal interface for the same to make it more efficient for testing.

**Comment by ranguy9304** [comment]
- [x] - Remove manual context generation and let the tools execute as needed.
- [x] - EmbeddingRetriever Class is in agent.py file move it or create a new module for the same
- [x] - Some unidentified problem with EmbeddingRetriever fix that.
- [x] - Due to the continuous execution of streamlit many initializations functions are called repeatedly, create a terminal interface for the same to make it more efficient for testing.
